services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb

  app:
    image: python
    links:
      - influxdb

  dashboard:
    image: grafana/grafana
    links:
      - app
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana

volumes:
  influxdb:
  grafana:
